import type { ReminderSound } from './reminder-rules';

/**
 * The audio clip each tone maps to, generated by
 * scripts/generate-alert-sounds.ts and served from /public.
 *
 * Only used when the app is open — a locked phone plays the operating system's
 * notification sound, which no PWA can override. SILENT has no file by design.
 */
export const SOUND_FILES: Record<ReminderSound, string | null> = {
  CHIME: '/sounds/chime.wav',
  BELL: '/sounds/bell.wav',
  ALARM: '/sounds/alarm.wav',
  SILENT: null,
};
